import project.com.controller.ComplainController
import project.com.controller.CropController
import project.com.controller.CropTypeController
import project.com.controller.DatasetController
import project.com.controller.FeedbackController
import project.com.controller.LoginController
import project.com.controller.MedicineCrontroller
import project.com.controller.RegisterController
import project.com.controller.PublicController
import project.com.controller.ImageController
import project.com.controller.DetectionController
import project.com.controller.AgricultureDirectoryController
